name: getx_template
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  gap: ^3.0.1
  cloud_firestore: ^5.4.2
  get_storage: ^2.1.1
  http: ^1.2.2
  http_interceptor: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0




flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/font/
    - assets/images/
    - assets/images/banner/
    - assets/lotties/
