// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD_SrZu5DPHH_yyyLlPUF3b3-om6nLx0PQ',
//     appId: '1:116744113428:web:8fb6fbf0dd7616cfe00601',
//     messagingSenderId: '116744113428',
//     projectId: 'habib-quiz',
//     authDomain: 'habib-quiz.firebaseapp.com',
//     storageBucket: 'habib-quiz.appspot.com',
//     measurementId: 'G-79JHHCB0HP',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCV6DgBYhazz2IzCAwZltvgZsn6ECDuZ5s',
//     appId: '1:116744113428:android:33de6bde80c2dfade00601',
//     messagingSenderId: '116744113428',
//     projectId: 'habib-quiz',
//     storageBucket: 'habib-quiz.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDnqGi913bzerA-ISj50Ti4qJcToO3xTFs',
//     appId: '1:116744113428:ios:e93d8b408a84dd5ee00601',
//     messagingSenderId: '116744113428',
//     projectId: 'habib-quiz',
//     storageBucket: 'habib-quiz.appspot.com',
//     iosBundleId: 'com.habibquiz.habibQuiz',
//   );
// }
